---
- name: Generate admin password
  shell: env LC_ALL=C tr -dc a-zA-Z0-9 < /dev/urandom | head -c 32 ; echo
  register: admin_pwd

- name: Generate postgres password
  shell: env LC_ALL=C tr -dc a-zA-Z0-9 < /dev/urandom | head -c 32 ; echo
  register: postgres_pwd

- name: Write admin_pwd to .env file
  copy: 
    content: "ADMIN_PWD={{ hostvars['localhost']['admin_pwd']['stdout'] }}"
    dest: ./.env

- name: Write postgres_pwd to .env file
  lineinfile: 
    line: "POSTGRES_PWD={{ hostvars['localhost']['postgres_pwd']['stdout'] }}"
    path: ./.env

- name: Indicate that it is a swarm deployment
  lineinfile: 
    line: "BROKERS_IN_CLUSTER={{ groups['workers'] | length }}"
    path: ./.env

- name: Set erlang cookie for all rabbitmq nodes to use
  vars:
    pwd_alias: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
  lineinfile: 
    line: "ERLANG_COOKIE={{ pwd_alias }}"
    path: ./.env

- name: Enable quick install mode
  lineinfile: 
    line: "QUICK_INSTALL=true"
    path: ./.env

- name: Enable quick install mode
  lineinfile: 
    line: "CLUSTER_WITH=rabbit1"
    path: ./.env

- name: Compress current repo into an archive
  archive:
    path:
    - ../api-server/
    - ../authenticator
    - ../clustered-setup/
    - ../conf/
    dest: ./vermillion.zip
    format: zip
