sudo: required

dist: xenial

before_install:
  - ./test-suite/require.sh

language: python

python: 2.7

install:
  - ./single-node/quick_install

before_script:
  - sleep 15
  - cd test-suite
  - git pull origin master
  - cd ..

script:
  - ./test-suite/test functional --random
  - ./test-suite/test security
  - ./test-suite/test concurrency
