version: "3"

networks:
  iudx-net:
    driver: bridge

volumes:
  pgsql-data:
  broker-data:
  mongo-data:

services:

  vertx:
    image: iudx/vertx
    container_name: vertx
    hostname: vertx
    restart: on-failure
    hostname: vertx
    ports:
      - "443:8443"
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - ../iudx-api-server:/iudx-api-server/
    env_file:
      - .env
    environment:
     - WAIT_HOSTS=postgres:5432,rabbit:5672,authenticator:80
     - WAIT_HOSTS_TIMEOUT=120

  authenticator:
    image: iudx/authenticator
    container_name: authenticator
    hostname: authenticator
    restart: on-failure
    hostname: authenticator
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - ../iudx-authenticator:/iudx-authenticator/
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=120

  rabbit:
    image: rabbitmq:3.7.18
    container_name: rabbit
    restart: on-failure
    hostname: rabbit
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - broker-data:/var/lib/rabbitmq/
      - ../conf/rabbitmq/:/etc/rabbitmq/
    env_file:
      - .env
  
  postgres:
    image: iudx/postgres
    container_name: postgres
    hostname: postgres
    restart: on-failure
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - pgsql-data:/var/lib/postgresql
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - "54321:27017"
    restart: on-failure
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

  dbconnector:
    image: iudx/db-connector
    container_name: connector
    hostname: connector
    restart: on-failure
    networks:
      - iudx-net
    volumes:
      - ../db-connector:/db-connector/
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432,rabbit:5672,authenticator:80,mongo:27017
      - WAIT_HOSTS_TIMEOUT=120

  unbind-daemon:
    image: iudx/unbind-daemon
    container_name: daemon
    hostname: daemon
    restart: on-failure
    networks:
      - iudx-net
    volumes:
      - ../unbind-daemon:/unbind-daemon/
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432,authenticator:80,rabbit:5672
      - WAIT_HOSTS_TIMEOUT=120
