version: "3"

volumes:
  pg-data:

services:
  auth:
    image: datasetu/auth-server
    container_name: auth.local
    hostname: auth.local
    ports:
      - "8443:443"
    restart: on-failure
    volumes:
      - ../auth-server/:/auth-server/
    networks:
      - vermillion-net
    env_file:
      - vermillion.conf

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    hostname: postgres
    restart: on-failure
    networks:
      - vermillion-net
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ../auth-server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - vermillion.conf
