version: "3"

networks:
  iudx-net:
    driver: bridge

volumes:
  pgsql-data:
  broker-data:
  elk-data:

services:

  vertx:
    image: iudx/vertx
    container_name: vertx
    hostname: vertx
    restart: always
    hostname: vertx
    ports:
      - "443:8443"
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - ../iudx-api-server:/iudx-api-server/
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432,rabbit:5672,authenticator:80

  authenticator:
    image: iudx/authenticator
    container_name: authenticator
    hostname: authenticator
    restart: always
    hostname: authenticator
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - ../iudx-authenticator:/iudx-authenticator/
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432

  rabbit:
    image: iudx/rabbitmq
    container_name: rabbit
    restart: always
    hostname: rabbit
    ports:
      - "5671:5671"
      - "15672:15672"
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - broker-data:/var/lib/rabbitmq/
      - ../conf/rabbitmq/:/etc/rabbitmq/
    env_file:
      - .env
  
  postgres:
    image: iudx/postgres
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - pgsql-data:/var/lib/postgresql
    env_file:
      - .env

  elk:
    image: nshou/elasticsearch-kibana
    container_name: elk
    hostname: elk
    ports:
      - "9200:9200"
      - "5601:5601"
    restart: always
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - elk-data:/home/ideam/elasticsearch-6.2.4

  dbconnector:
    image: iudx/dbconnector
    container_name: dbconnector
    hostname: dbconnector
    restart: always
    hostname: dbconnector
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - ../iudx-dbconnector:/iudx-dbconnector/
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432,rabbit:5672, elk:9200

  unbind-daemon:
    image: iudx/unbind-daemon
    container_name: daemon
    hostname: daemon
    restart: always
    hostname: daemon
    networks:
      - iudx-net
    cap_add:
      - ALL
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432,rabbit:5672
