version: "3"

networks:
  iudx-net:
    driver: bridge

volumes:
  pgsql-data:
  broker-data:
  es-data:

services:

  vertx:
    image: iudx/java
    container_name: vertx
    hostname: vertx
    restart: on-failure
    ports:
      - "443:8443"
    networks:
      - iudx-net
    volumes:
      - ../api-server:/api-server/
    env_file:
      - .env
    environment:
     - WAIT_HOSTS=postgres:5432,rabbit:5672,authenticator:80
     - WAIT_HOSTS_TIMEOUT=120
     - PROJECT_DIR=api-server
     - JAR_NAME=api-server-fat.jar

  authenticator:
    image: iudx/java
    container_name: authenticator
    hostname: authenticator
    restart: on-failure
    networks:
      - iudx-net
    volumes:
      - ../authenticator:/authenticator/
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=120
      - PROJECT_DIR=authenticator
      - JAR_NAME=authenticator-fat.jar

  rabbit:
    image: rabbitmq:3.8.3
    container_name: rabbit
    restart: on-failure
    hostname: rabbit
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    networks:
      - iudx-net
    volumes:
      - broker-data:/var/lib/rabbitmq/
      - ../conf/rabbitmq/:/etc/rabbitmq/
    env_file:
      - .env
  
  postgres:
    image: iudx/postgres
    container_name: postgres
    hostname: postgres
    restart: on-failure
    networks:
      - iudx-net
    volumes:
      - pgsql-data:/var/lib/postgresql
    env_file:
      - .env

  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
    restart: on-failure
    networks:
      - iudx-net
    volumes:
      - es-data:/usr/share/elasticsearch/data
    env_file:
      - .env
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    restart: on-failure
    networks:
      - iudx-net

  dbconnector:
    image: iudx/db-connector
    container_name: connector
    hostname: connector
    restart: on-failure
    networks:
      - iudx-net
    volumes:
      - ../db-connector:/db-connector/
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432,rabbit:5672,authenticator:80,elasticsearch:9200
      - WAIT_HOSTS_TIMEOUT=600

  unbind-daemon:
    image: iudx/unbind-daemon
    container_name: daemon
    hostname: daemon
    restart: on-failure
    networks:
      - iudx-net
    volumes:
      - ../unbind-daemon:/unbind-daemon/
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=postgres:5432,authenticator:80,rabbit:5672
      - WAIT_HOSTS_TIMEOUT=120
