version: "3"

services:
  kibana:
    image: kibana:${KIBANA_VERSION}
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    restart: on-failure
    networks:
      - vermillion-net
