openapi: 3.0.3
info:
  version: 1.0.0
  title: Vermilllion API Documentaion
  termsOfService: 'test'
  contact: 'test'
    email: 'test'
    url: 'test'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description: 'test'
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Consumer
    description: This is a data consumer information.
  - name: Provider
    description: This is a data provider information.

servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'

paths:

  /download:
    post:
      tags:
       - Consumer
      description: This endpoint gives a consumer accesss to download the data.
      operationId: download
      parameters:
        - name: token
          in: query
          required: true
          description: token given by auth server to consumer
          schema:
            type: string
            example: ""
        - name: requestedIds
          in: query
          required: true
          description: requestedIds given by consumer
          schema:
            type: string
            example: ""
      responses:
        200:
          description: The consumer gets the data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/download'

security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
  schemas:
    download:
     description: "schema for download"
     type: string
     properties:
       data:
        type: string
        example: "Testing now"




