version: "3"

networks:
  iudx-net:
    driver: bridge

volumes:
  pgsql-data:
  broker-data:

services:

  vertx:
    image: ideam/vertx
    container_name: vertx
    hostname: vertx
    restart: always
    hostname: vertx
    ports:
      - "443:8443"
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - ../iudx-api-server:/iudx-api-server/
      - ../setup/vertx:/scripts/
      - ../vars/:/vars/
    env_file:
      - .env

  broker:
    image: ideam/kore-broker
    container_name: broker 
    restart: always
    hostname: broker
    ports:
      - "5671:5671"
      - "1883:1883"
      - "15672:15672"
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - broker-data:/var/lib/rabbitmq/
      - ../authenticator:/authenticator/
      - ../rabbitmq:/etc/rabbitmq/
      - ../setup/broker:/scripts/
      - ../vars/:/vars/
    env_file:
      - .env
  
  postgres:
    image: ideam/postgres
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - pgsql-data:/var/lib/postgresql
      - ../setup/pgsql:/scripts/
      - ../vars/:/vars/
    env_file:
      - .env
