---
- name: Generate admin password
  shell: cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32; echo
  register: admin_pwd

- name: Generate postgres password
  shell: cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32; echo
  register: postgres_pwd

- name: Write admin_pwd to .env file
  copy: 
    content: "ADMIN_PWD={{ hostvars['localhost']['admin_pwd']['stdout'] }} "
    dest: ./.env

- name: Write postgres_pwd to .env file
  lineinfile: 
    line: "POSTGRES_PWD={{ hostvars['localhost']['postgres_pwd']['stdout'] }} "
    path: ./.env

- name: Indicate that it is a swarm deployment
  lineinfile: 
    line: "BROKERS_IN_SWARM={{ groups['workers'] | length -1 }}"
    path: ./.env
