---
- name: Install Docker dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags: docker

- name: Get Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker packages to repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker

- name: Install Docker-CE
  apt: name="docker-ce" state=latest update_cache=yes
  tags: docker

- name: Install python3 python3-pip python3-setuptools
  apt:
    name: ["python3", "python3-pip", "python3-setuptools"]

- name: Install docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Apply executable permissions to the binary
  shell: chmod +x /usr/local/bin/docker-compose

- name: Leave any previously joined swarm
  shell: docker swarm leave --force
  ignore_errors: true

- cron:
    name: Join swarm after system restart
    special_time: reboot
    job: "docker ps"

- name: Check if the git repository exists
  stat:
    path: /root/iudx-resource-server/
  register: repo

- name: Delete the reository if it already exists
  file:
    state: absent
    path: /root/iudx-resource-server
  when: repo.stat.exists

- name: Clone the repository
  shell: git clone https://github.com/rbccps-iisc/iudx-resource-server/

- name: Initialise submodules
  shell: 
    cmd: git submodule init
    chdir: /root/iudx-resource-server

- name: Update submodules
  shell: 
    cmd: git submodule update
    chdir: /root/iudx-resource-server

- name: Copy docker-compose.json file
  copy:
    src: ./docker-compose.json
    dest: /root/iudx-resource-server/swarm/

- name: Copy .env file
  copy:
    src: ./.env
    dest: /root/iudx-resource-server/swarm/
