---
- name: Install Docker dependencies
  apt: 
    name: ["apt-transport-https", "zip", "unzip", "ca-certificates", "curl", "software-properties-common"]
    state: latest
    update_cache: yes
  tags: docker

- name: Get Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker packages to repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker

- name: Install Docker-CE
  apt: name="docker-ce" state=latest update_cache=yes
  tags: docker

- name: Install python3 python3-pip python3-setuptools
  apt:
    name: ["python3", "python3-pip", "python3-setuptools"]

- name: Install docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Apply executable permissions to the binary
  shell: chmod +x /usr/local/bin/docker-compose

- name: Leave any previously joined swarm clusters
  shell: docker swarm leave --force
  ignore_errors: true

- cron:
    name: Join swarm after system restart
    special_time: reboot
    job: "docker ps"

- name: Check if the git repository exists
  stat:
    path: ~/iudx-resource-server/
  register: repo

- name: Delete the repository if it already exists
  file:
    state: absent
    path: ~/iudx-resource-server/
  when: repo.stat.exists

- name: Create iudx-resource-server folder
  file:
    path: ~/iudx-resource-server/
    state: directory

- name: Unarchive repo on remote hosts
  unarchive:
    src: ./iudx.zip
    dest: ~/iudx-resource-server
    creates: ~/iudx-resource-server/deploy

- name: Cleanup existing docker stuff
  shell: docker system prune -a -f
  ignore_errors: true

- name: Add options to /etc/sysctl.conf
  shell: cat ~/iudx-resource-server/conf/sysctl/sysctl.conf >> /etc/sysctl.conf

- name: Set sysctl File Limits
  copy:
    src: ../conf/sysctl/50-fs.conf
    dest: /etc/sysctl.d

- name: Set Shell File Limits
  copy:
    src: ../conf/sysctl/91-nofiles.conf
    dest: /etc/security/limits.d
