- name: Check if the git repository exists
  stat:
    path: /root/iudx-resource-server/
  register: repo

- name: Delete the reository if it already exists
  file:
    state: absent
    path: /root/iudx-resource-server
  when: repo.stat.exists

- name: Clone the repository
  shell: git clone https://github.com/rbccps-iisc/iudx-resource-server/

- name: Initialise submodules
  shell: 
    cmd: git submodule init
    chdir: /root/iudx-resource-server

- name: Update submodules
  shell: 
    cmd: git submodule update
    chdir: /root/iudx-resource-server

- name: Copy docker-compose.json file
  copy:
    src: ./docker-compose.json
    dest: /root/iudx-resource-server/swarm/

- name: Copy .env file
  copy:
    src: ./.env
    dest: /root/iudx-resource-server/swarm/

- name: Deploy stack
  shell:     
    cmd: docker stack deploy -c docker-compose.json iudx-resource-server
    chdir: /root/iudx-resource-server/swarm/
