---
- name: Install docker
  apt:
    name: docker.io
    update_cache: yes
    
- name: Install build-essential 
  apt:
    name: build-essential
    update_cache: yes

- name: Install python3 python3-pip python3-setuptools
  apt:
    name: ["python3", "python3-pip", "python3-setuptools"]

- name: Install docker-compose
  pip:
    name: docker-compose

- name: Leave any previously joined swarm
  shell: docker swarm leave --force
  ignore_errors: true

- cron:
    name: Join swarm after system restart
    special_time: reboot
    job: "docker ps"
    
