name: test-suite

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

    - name: Set log level to "FINE" in apiserver
      run: sed -i 's/INFO/FINEST/g' api-server/src/main/resources/vertx-default-jul-logging.properties

    - name: Set log level to "FINE" in authenticator
      run: sed -i 's/INFO/FINEST/g' authenticator//src/main/resources/vertx-default-jul-logging.properties

    - name: Compile api server source files
      run: cd api-server && mvn clean package

    - name: Compile authenticator source files 
      run: cd authenticator && mvn clean package

    - name: Install jq and behave
      run: apt -y install jq && python3 -m pip install behave

    - name: Install Vermillion
      run: ./single-node/install

    - name: Wait for the middleware to be available
      run:  sleep 15

    - name: Run tests
      run:  cd ./tests/single-node/ && behave

    - name: Export docker logs to a file
      if: always()
      run: docker logs vertx >& logs.txt

    - name: Upload file 'logs.txt' as an artifact
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: pass_file
        path: logs.txt
